### ISSUE TITLE
Waiter object returned from callWaiter on 0.4.2

### ISSUE THREAD

**Issue by seesleestak** [hixme/redux-waiter#37]
Prior to `0.4.2`, `callWaiter` returned the response from the `requestCreator`. We could do something like this:
```
dispatch(
  callWaiter("waiter-name", {
    requestCreator: () => axios.get("/my-endpoint")
  })
).then((res) => {
  console.log("Axios response --- ", res)
})
```

On `0.4.2`, `callWaiter` now returns the waiter object. I've investigated the cause a bit, but haven't gotten anything so far.

**Comment by seesleestak** [comment]
I'm seeing that when I modify the `callWaiter` return to this, the old functionality returns.
```
request
  .then((data) =>
    dispatch(
      waiterResponseHandler(name, {
        waiterId,
        responseAction: resolveRequest,
        responseData: data,
      })
    )
  )
  .catch((error) =>
    dispatch(
      waiterResponseHandler(name, {
        waiterId,
        responseAction: rejectRequest,
        responseData: error,
      })
    )
  );

return request;
```

I'm guessing it was blowing through the promise handling here before and now that we're returning the request directly, the `callWaiter` return is now what I'm guessing it was intended to be from the start (?). What are your thoughts on this?

**Comment by billyxs** [comment]
Good catch! That did change the functionality.

My general view is that I think it's strange for someone calling this 
```
dispatch(
  callWaiter("waiter-name", {
    requestCreator: () => axios.get("/my-endpoint")
  }).then((res) => {...})
```

...to receive something different than what the `connectWaiter()` component might render if for some reason the call is `cleared` or `canceled` or a new call is made.  Could be a "warning" in the docs that it's outside the state manager.

Another issue that change created is that it probably doesn't end up in a `catch()` for the caller, since the error is never thrown.

**Comment by seesleestak** [comment]
It's not the end of the world to just dig into the `response` within the waiter object to get the same return object for my use case. I just wanted to explore exactly what we were expecting to return there. If the intention was to return the waiter object like we have now, I have no problems just updating the implementation.

**Comment by billyxs** [comment]
I like the idea of the user getting the `waiter` store as a response. Gives more context to the caller of what kind of result they are receiving, what the state of the store was when it returned.  Question would then be, should it always succeed? If you throw and error, does it make sense to get back the waiter object or an error response?

**Comment by seesleestak** [comment]
The error response should get loaded into the waiter `response` right? So the error response from the call is accessible in the waiter object. But then the waiter would have to throw in order to make `callWaiter` fail out?

**Comment by billyxs** [comment]
> The error response should get loaded into the waiter `response` right? So the error response from the call is accessible in the waiter object. But then the waiter would have to throw in order to make `callWaiter` fail out?

If there is an `error`, waiter `response` will be null and the waiter `error` property will have the thrown `error`...if that's what you mean...yes!

Right, the request would have to throw to signify that the lifecycle of the Promise was ultimately `rejected`.

**Comment by seesleestak** [comment]
> If there is an `error` as the result of the `catch`, waiter `response` will be null and the waiter `error` property will have the thrown `error`...if that's what you mean...yes!

That's definitely what I meant :)

**Comment by seesleestak** [comment]
How would you feel about me doing a patch release to publish the old functionality with the `then` fix and then publishing a minor release after that to _fix_ the old functionality as discussed. That way, I can get that little promise fix without having to migrate anything?

**Comment by billyxs** [comment]
yeah, no problem at all. I assumed you were working on it 😄

**Comment by seesleestak** [comment]
Cool, I'll take care of it. Just hadn't gotten the chance yet :)
